[project]
name = "ai-task-manager"
version = "0.1.0"
description = "A task manager that uses AI to help users manage their tasks through natural language"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
